excluded:
  - Carthage
  - Package.swift
  - Consumption-Tests/*/Carthage
  - Consumption-Tests/*/Pods
  # Bitrise SwiftLint workaround (Bitrise stopped respecting nested .swiftlint.yml files)
  - Tests
  - Consumption-Tests

identifier_name:
  excluded:
  - id
  - ex
  - to
  - ws

# This generates a compiler error if more than this many SwiftLint warnings are present
# (This threshold can become more restrictive as remaining warnings are resolved via refactoring)
warning_threshold: 21